<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(FrameworkVersion)</TargetFramework>
    <TargetVintageStory>server:$(VintageStoryVersion)</TargetVintageStory>
    <OutputType>Exe</OutputType>
    <OutputPath>bin</OutputPath>
    <Optimize>false</Optimize>
    <DebugType>none</DebugType>
    <RunWorkingDirectory>$(MSBuildProjectDirectory)/..</RunWorkingDirectory>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishSelfContained>true</PublishSelfContained>
    <PublishDocumentationFiles>false</PublishDocumentationFiles>
    <PublishReferencesDocumentationFiles>false</PublishReferencesDocumentationFiles>
    <PublishReferencesSymbols>false</PublishReferencesSymbols>
    <PublishDir>../bin</PublishDir>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cake.Frosting" Version="6.1.0" />
    <PackageReference Include="Cake.Json" Version="7.0.1" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <Reference Include="VintagestoryAPI">
      <HintPath>$(VintageStoryPath)/VintagestoryAPI.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
